# Generated by Django 2.0.9 on 2018-11-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_app',
            name='app_category',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
